### PR TITLE
Mavenize

### PR DESCRIPTION
**Pull request by SoSeDiK**
- It supposed to be a 1.13 update but there was almost nothing to change.
  - Note: I did not update enchantments because CS-CoreLib still uses names instead of namespace keys.
- Mavenize!
  - Would be great to see it in builds page.

@TheBusyBiscuit, do you still have sources of any other Slimefun addons that weren't posted on GitHub yet? I would be very happy to see them.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
@SoSeDiK For the moment, I am not going to add this to the builds page.
And probably, whbat addons do you have in mind?

**Comment by SoSeDiK** [comment]
Mostly I'm interested in SF Barrels.
And my players ask for Electric Spawners & Soul Jars.
Also, I don't have John00708's contacts, I would like to use almost all of his addons.

**Comment by TheBusyBiscuit** [comment]
@SoSeDiK Electric Spawners and Soul Jars I should still have.
For John's plugins, look at his github page, most of them are open-source (Including Barrels).
https://github.com/John000708

**Comment by TheBusyBiscuit** [comment]
@SoSeDiK 

https://github.com/TheBusyBiscuit/ElectricSpawners
https://github.com/TheBusyBiscuit/SoulJars

**Pull request merged**
